### PR TITLE
Fixes #5531 Circular Progress bar keeps on moving when nomination for deletion is successful.

### LINKED ISSUE #5531: [Bug]: Circular Progress bar keeps on moving even though nomination for deletion is successful
### Summary

When the user clicks on 'Nominate for Deletion,' the circular progress bar keeps moving even though the nomination for deletion is successful. This doesn't provide any visible status and makes the user think that the process is ongoing. Only a notification is received, which can be piled up among other notifications.

### Steps to reproduce

1. Open the App
2. Click on any contribution
3. Click on Nominate for Deletion

### Expected behaviour

OnSuccess : Circular Progress bar should stop and Text should change to nominated for deletion

### Actual behaviour

OnSuccess : Circular Progress bar keeps on moving

### Device name

Samsung S21

### Android version

Android 14

### Commons app version

4.2.1-debug-HEAD~d4b473656

### Device logs

_No response_

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/114223204/f215652b-00a3-4256-8c34-c90eeadf31c0

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by neeldoshii**
## Fixes
* Fixes #5531. 

## Description
This pull request addresses an issue where the circular progress bar remains active and keeps moving even after a nomination for deletion is successful.  The fix ensures that the progress bar is hidden and the UI is updated correctly upon successful deletion also the Snackbar is shown when the nomination is done successfully.

## Changes
- Modified the `onDeleteClicked()` & `onDeleteClickeddialogtext`  & created a `handleDeletionResult()` for handling what to do on success, created a `handleDeletionError()` for handling what to do on failure. 
- Ensured that UI updates are performed on the UI thread to prevent potential `CalledFromWrongThreadException`.

### Steps to Test
1. Open the app.
2. Open any contribution.
3. Click on the nomination for deletion.
4. Observe the progress bar behavior after the nomination process completes.

### Expected Results
- The circular progress bar should disappear, indicating that the process has completed.
- The user should see a confirmation message indicating the successful nomination for deletion.

## Additional Information
- Tested on both emulators and physical devices to verify the fix.

### CODE REVIEW

**Comment by neeldoshii** [comment]
Just a friendly ping @nicolas-raoul @RitikaPahwa4444 , can you please Review this pr and let me know if there is any change required.

**Comment by nicolas-raoul** [comment]
Very strangely, even though CI is running fine, I am getting this when building, any idea why?
```
> Task :app:compileProdDebugJavaWithJavac
The following annotation processors are not incremental: dagger-android-processor-2.23.jar (com.google.dagger:dagger-android-processor:2.23), dagger-compiler-2.23.jar (com.google.dagger:dagger-compiler:2.23).
Make sure all annotation processors are incremental to improve your build speed.
/Users/nicolasraoul/src/commons-app/app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:1235: error: cannot find symbol
            if (progressBarDeletion != null) {
                ^
  symbol:   variable progressBarDeletion
  location: class MediaDetailFragment
/Users/nicolasraoul/src/commons-app/app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:1236: error: cannot find symbol
                progressBarDeletion.setVisibility(GONE);
                ^
  symbol:   variable progressBarDeletion
  location: class MediaDetailFragment
/Users/nicolasraoul/src/commons-app/app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:1244: error: cannot find symbol
            delete.setText("Nominated for Deletion");
            ^
  symbol:   variable delete
  location: class MediaDetailFragment
  ```

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
CI unfortunately fails after rebasing on the mnain branch.
Would you mind fixing?
Thanks a lot! :-)

**Comment by rohit9625** [comment]
Hey @neeldoshii, any updates on this PR? If you're not available then I can help you fix the issues. Just let know :)

**Comment by rohit9625** [comment]
I guess, I'll need to write permissions to your branch to be able to commit changes. Would you mind giving me the write permissions?

**Comment by nicolas-raoul** [comment]
Thanks both!

@rohit9625 The best is for you to start a new branch and pull from this one. :-) Also, could you please comment at https://github.com/commons-app/apps-android-commons/issues/5531 so that I can assign you?

**Comment by nicolas-raoul** [comment]
Many features do not work on beta, this might indeed be one of them.

**Comment by neeldoshii** [comment]
> When testing, is the image marked for nomination successfully? I'm testing on BetDebug and found that the getAchievements function is failing silently.

Hi @rohit9625, yes for working on Nomination for deletion works only on prod and achievements feature is also only available for prod. Just note don't perform mass deletion you might get banned from wikimedia as I got banned 2 years back.

> I guess, I'll need write permissions to your branch to be able to commit changes. Would you mind giving me the write permissions? Also, please unmark it as Draft PR.

Sure, any idea how can I give you write permission for a specific branch?

**Comment by neeldoshii** [comment]
Ok. I am closing this PR as the work is now carried forward on #6324. Thanks @rohit9625
