### ISSUE TITLE
Error on updating mapbox map

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3066]
**Summary:** 

Hi all, currently our mapbox is not up to date, but I am facing with some issues when I try update it.

**Steps to reproduce:** 

We have these two lines at build gradle:
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.8.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization:0.6.0'
```
And I change them with these two:
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v8:0.10.0'
```
Sync is successful, however it complains about  some kotlin issues on run:
![image](https://user-images.githubusercontent.com/3127881/61172010-c709ff80-a587-11e9-8e0d-a3fe018251b4.png)

But I think this issues seems irrelevant, do you know what can be cause of this. 

**System logs:**

Some logs:
```
/home/nes/AndroidStudioProjects/CommonsApp9/apps-android-commons/app/src/main/java/fr/free/nrw/commons/review/ReviewInterface.java:17: error: cannot find symbol
    Observable<MwQueryResponse> getFirstRevisionOfFile(@Query("titles") String titles);
                                                        ^
  symbol:   class Query
  location: interface ReviewInterface

```

**Device and Android version:** 

API 26 nexus emulator, beta debug

**Comment by maskaravivek** [comment]
@neslihanturan is retrofit dependency added in the gradle file? Can I see the code somewhere?

**Comment by neslihanturan** [comment]
Sure @maskaravivek , I created a branch on my fork: https://github.com/neslihanturan/apps-android-commons/tree/updateMapbox

**Comment by maskaravivek** [comment]
@neslihanturan Can you check the migration guide. Earlier we were using 6.X version and now we are changing it to 8.1. There are some migration steps that need to be followed when migration from 6.X. 

https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide

Also, as described [here](https://docs.mapbox.com/android/maps/overview/), you might have to exclude some conflicting modules like this: 

```
implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0'){
    exclude group: 'group_name', module: 'module_name'
}
```

**Comment by neslihanturan** [comment]
Hi @maskaravivek , I have followed docs but I think we are okay according to migration guide. 
Our dependency tree when we try to update it to version 8 as:
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v8:0.10.0'
```
 is:
```
+--- com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:4.5.1
|    |    +--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.12.1 (*)
|    |    +--- com.google.code.gson:gson:2.8.5
|    |    +--- com.mapbox.mapboxsdk:mapbox-android-core:1.3.0
|    |    +--- androidx.annotation:annotation:1.0.0 -> 1.0.2
|    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:4.8.0
|    |    \--- com.google.code.gson:gson:2.8.5
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.4.2
|    |    \--- androidx.core:core:1.0.0 -> 1.1.0-alpha03 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.2.0
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.0.2
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-turf:4.8.0
|    |    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:4.8.0 (*)
|    +--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.12.1 (*)
```
Sync is succeed but it gives this error on build:
![image](https://user-images.githubusercontent.com/3127881/61310783-a77c0c80-a7fd-11e9-8058-8899921dcb85.png)
Logs doesn't mean much, there is nothing related with retrofit.

--------------------

I suspected that the problem can be about migration from 6.x to 7.x but everyting is okay when I use version 7 as:

```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.0.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v7:0.7.0'
```

No sync or build fails with version 7.

**Comment by neslihanturan** [comment]
Latest progress, I am able to update it up to 7.2.0 but problems starts at 7.3.0. Additionally updating it to 7.2.0 didn't fixed #3067 issue.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  this is a very old issue and we are using different dependencies now and this issue is not relevant any more

**Comment by nicolas-raoul** [comment]
Indeed, I see that we are already at `mapbox-android-sdk:9.1.0`.
Thanks @Rishavgupta12345 !
